<?php

namespace App\Services;

use App\Enums\OrderSource;
use App\Enums\OrderStatus;
use App\Models\Order;
use App\Models\User;

/**
 * Creates and moves merchant orders through their simple lifecycle
 * (new → in_progress → completed, or cancelled).
 */
class OrderService
{
    /**
     * Record a new order for a merchant. The tracker code is generated by the
     * model. Quota is enforced by the caller via OrderQuotaService.
     */
    public function create(User $merchant, array $data, OrderSource $source): Order
    {
        return $merchant->orders()->create([
            ...$data,
            'source' => $source,
            'status' => OrderStatus::New,
            'currency' => config('payments.currency', 'OMR'),
        ]);
    }

    /** Move an order to a new status, stamping the relevant timestamps. */
    public function updateStatus(Order $order, OrderStatus $status): Order
    {
        $order->status = $status;

        if ($status === OrderStatus::InProgress && $order->confirmed_at === null) {
            $order->confirmed_at = now();
        }

        if ($status === OrderStatus::Completed && $order->completed_at === null) {
            $order->completed_at = now();
        }

        $order->save();

        return $order;
    }
}
